// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arodjjenfgcewmxzqhxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyb2RqamVuZmdjZXdteHpxaHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTkxOTQsImV4cCI6MjA2OTczNTE5NH0.Vpr3yNSCir_1NVsJmbzsbuEc1Lmv_wxw3Qjwlh2j-8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});